#!/bin/env bash
echo 'instalando ...'
apt-get install -y python
echo 'instalando python ...'
pip install requests
echo 'instalando requests ...'
pip install colorama
echo 'instalado colorama ...'
pip install bs4
echo 'instalando beautifulsoup ...'
apt-get install -y nmap
echo 'Proceso terminado'
rm -rf instalar

